$schema: ../../../schema/modl.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  path: "./modl.log"
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    fetch:
      command: "uvx"
      args:
        directories:
          - "/"
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
